"""cascade delete

Revision ID: 20616cad136a
Revises: d63279449f83
Create Date: 2023-05-21 02:55:55.103676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20616cad136a'
down_revision = 'd63279449f83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk-pictures-post_id-posts', 'pictures', type_='foreignkey')
    op.create_foreign_key(op.f('fk-pictures-post_id-posts'), 'pictures', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk-posts-user_id-users', 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk-posts-user_id-users'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk-posts-user_id-users'), 'posts', type_='foreignkey')
    op.create_foreign_key('fk-posts-user_id-users', 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk-pictures-post_id-posts'), 'pictures', type_='foreignkey')
    op.create_foreign_key('fk-pictures-post_id-posts', 'pictures', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
