"""aspect ratio

Revision ID: 23244b6c2605
Revises: 4f504761ae6f
Create Date: 2023-05-27 12:30:48.448906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23244b6c2605'
down_revision = '4f504761ae6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('aspect_ratio', sa.Float(precision=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'aspect_ratio')
    # ### end Alembic commands ###
