"""messages

Revision ID: 4363401316c9
Revises: 6420773f9506
Create Date: 2023-06-04 19:37:29.946818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4363401316c9'
down_revision = '6420773f9506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-messages-post_id-posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-messages-user_id-users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-messages'))
    )
    op.add_column('users', sa.Column('avatar_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    op.drop_table('messages')
    # ### end Alembic commands ###
