"""marks

Revision ID: 4f504761ae6f
Revises: 9077654efec6
Create Date: 2023-05-23 01:18:40.738671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f504761ae6f'
down_revision = '9077654efec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-marks-post_id-posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-marks-user_id-users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
