"""cascade

Revision ID: 6420773f9506
Revises: e3d811644124
Create Date: 2023-05-28 13:39:20.929794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6420773f9506'
down_revision = 'e3d811644124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk-marks-user_id-users', 'bookmarks', type_='foreignkey')
    op.drop_constraint('fk-marks-post_id-posts', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('fk-bookmarks-post_id-posts'), 'bookmarks', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk-bookmarks-user_id-users'), 'bookmarks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk-bookmarks-user_id-users'), 'bookmarks', type_='foreignkey')
    op.drop_constraint(op.f('fk-bookmarks-post_id-posts'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key('fk-marks-post_id-posts', 'bookmarks', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('fk-marks-user_id-users', 'bookmarks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
