"""init migration

Revision ID: 8baebb814f80
Revises: 
Create Date: 2023-05-20 01:26:42.038942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baebb814f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-users')),
    sa.UniqueConstraint('email', name=op.f('uq-users-email')),
    sa.UniqueConstraint('username', name=op.f('uq-users-username'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-posts-user_id-users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-posts'))
    )
    op.create_table('pictures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-pictures-post_id-posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-pictures'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
