"""migration

Revision ID: 948ad59887ea
Revises: 
Create Date: 2023-06-14 01:22:21.874230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948ad59887ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avatar_id', sa.UUID(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-users')),
    sa.UniqueConstraint('email', name=op.f('uq-users-email')),
    sa.UniqueConstraint('username', name=op.f('uq-users-username'))
    )
    op.create_table('verify_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk-verify_codes'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.Column('aspect_ratio', sa.Float(precision=3), nullable=False),
    sa.Column('downloads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-posts-user_id-users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-posts'))
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-bookmarks-post_id-posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-bookmarks-user_id-users'), ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq-bookmarks-user_id.post_id'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-messages-post_id-posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-messages-user_id-users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-messages'))
    )
    op.create_table('pictures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-pictures-post_id-posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-pictures'))
    )
    op.create_table('views',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-views-post_id-posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-views-user_id-users'), ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq-views-user_id.post_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views')
    op.drop_table('pictures')
    op.drop_table('messages')
    op.drop_table('bookmarks')
    op.drop_table('posts')
    op.drop_table('verify_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
