"""statistics

Revision ID: a1dc392b757a
Revises: 23244b6c2605
Create Date: 2023-05-28 00:48:11.641329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dc392b757a'
down_revision = '23244b6c2605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('downloads', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'downloads')
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
