"""views

Revision ID: d1c5440f9b0e
Revises: 4363401316c9
Create Date: 2023-06-04 20:08:43.034873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c5440f9b0e'
down_revision = '4363401316c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk-views-post_id-posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk-views-user_id-users'), ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq-views-user_id.post_id'))
    )
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('views')
    # ### end Alembic commands ###
