"""verify codes

Revision ID: d63279449f83
Revises: 8baebb814f80
Create Date: 2023-05-20 15:04:23.985026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63279449f83'
down_revision = '8baebb814f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk-verify_codes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_codes')
    # ### end Alembic commands ###
