"""unique bookmarks

Revision ID: e3d811644124
Revises: a1dc392b757a
Create Date: 2023-05-28 01:12:40.222493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d811644124'
down_revision = 'a1dc392b757a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq-bookmarks-user_id.post_id'), 'bookmarks', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq-bookmarks-user_id.post_id'), 'bookmarks', type_='unique')
    # ### end Alembic commands ###
